// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: pb/shortener.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShortenURLRequest is request with URL
type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_pb_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ShortenURLResponse is response with shortened URL
type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_pb_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// ShortenURLJSONRequest is request with URL in json format
type ShortenURLJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLJSONRequest) Reset() {
	*x = ShortenURLJSONRequest{}
	mi := &file_pb_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLJSONRequest) ProtoMessage() {}

func (x *ShortenURLJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLJSONRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLJSONRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenURLJSONRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ShortenURLJSONResponse is response with shortened URL in json format
type ShortenURLJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLJSONResponse) Reset() {
	*x = ShortenURLJSONResponse{}
	mi := &file_pb_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLJSONResponse) ProtoMessage() {}

func (x *ShortenURLJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLJSONResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLJSONResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenURLJSONResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// GetOriginalURLRequest is request with shortened URL
type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_pb_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *GetOriginalURLRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// GetOriginalURLResponse is response with original URL
type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_pb_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetOriginalURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// BatchURL is item for batch processing
type BatchURLItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLItem) Reset() {
	*x = BatchURLItem{}
	mi := &file_pb_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLItem) ProtoMessage() {}

func (x *BatchURLItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLItem.ProtoReflect.Descriptor instead.
func (*BatchURLItem) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *BatchURLItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchURLItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// BatchURLRequest request contains urls for batch processing
type BatchURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrigUrls      []*BatchURLItem        `protobuf:"bytes,1,rep,name=orig_urls,json=origUrls,proto3" json:"orig_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLRequest) Reset() {
	*x = BatchURLRequest{}
	mi := &file_pb_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLRequest) ProtoMessage() {}

func (x *BatchURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLRequest.ProtoReflect.Descriptor instead.
func (*BatchURLRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *BatchURLRequest) GetOrigUrls() []*BatchURLItem {
	if x != nil {
		return x.OrigUrls
	}
	return nil
}

// BatchURLResponse response contains shortened urls as result batch processing
type BatchURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []*BatchURLItem        `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLResponse) Reset() {
	*x = BatchURLResponse{}
	mi := &file_pb_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLResponse) ProtoMessage() {}

func (x *BatchURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLResponse.ProtoReflect.Descriptor instead.
func (*BatchURLResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *BatchURLResponse) GetShortUrls() []*BatchURLItem {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

// UserURLItem represents user's url(short and original)
type UserURLItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLItem) Reset() {
	*x = UserURLItem{}
	mi := &file_pb_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLItem) ProtoMessage() {}

func (x *UserURLItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLItem.ProtoReflect.Descriptor instead.
func (*UserURLItem) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *UserURLItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURLItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// GetUserURLRequest is empty request
type GetUserURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLRequest) Reset() {
	*x = GetUserURLRequest{}
	mi := &file_pb_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLRequest) ProtoMessage() {}

func (x *GetUserURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{10}
}

// GetUserURLResponse is response with user's url
type GetUserURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURLItem         `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLResponse) Reset() {
	*x = GetUserURLResponse{}
	mi := &file_pb_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLResponse) ProtoMessage() {}

func (x *GetUserURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserURLResponse) GetUrls() []*UserURLItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

// DeleteUserURLRequest is request with id's of shortened url
type DeleteUserURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []string               `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLRequest) Reset() {
	*x = DeleteUserURLRequest{}
	mi := &file_pb_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLRequest) ProtoMessage() {}

func (x *DeleteUserURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserURLRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

// DeleteUserURLResponse is empty response
type DeleteUserURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLResponse) Reset() {
	*x = DeleteUserURLResponse{}
	mi := &file_pb_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLResponse) ProtoMessage() {}

func (x *DeleteUserURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{13}
}

// StatsRequest is empty request
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_pb_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{14}
}

// StatsResponse is response contains all shortened urls and users in the service
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_pb_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{15}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

// PingRequest is ping request
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_pb_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{16}
}

// PingResponse is response with the result of checking the connection to the database
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_pb_shortener_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortener_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_pb_shortener_proto_rawDescGZIP(), []int{17}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_pb_shortener_proto protoreflect.FileDescriptor

const file_pb_shortener_proto_rawDesc = "" +
	"\n" +
	"\x12pb/shortener.proto\x12\tshortener\"%\n" +
	"\x11ShortenURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"1\n" +
	"\x12ShortenURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\")\n" +
	"\x15ShortenURLJSONRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"5\n" +
	"\x16ShortenURLJSONResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"4\n" +
	"\x15GetOriginalURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\";\n" +
	"\x16GetOriginalURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"G\n" +
	"\fBatchURLItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"G\n" +
	"\x0fBatchURLRequest\x124\n" +
	"\torig_urls\x18\x01 \x03(\v2\x17.shortener.BatchURLItemR\borigUrls\"J\n" +
	"\x10BatchURLResponse\x126\n" +
	"\n" +
	"short_urls\x18\x01 \x03(\v2\x17.shortener.BatchURLItemR\tshortUrls\"M\n" +
	"\vUserURLItem\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"\x13\n" +
	"\x11GetUserURLRequest\"@\n" +
	"\x12GetUserURLResponse\x12*\n" +
	"\x04urls\x18\x01 \x03(\v2\x16.shortener.UserURLItemR\x04urls\"5\n" +
	"\x14DeleteUserURLRequest\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x01 \x03(\tR\tshortUrls\"\x17\n" +
	"\x15DeleteUserURLResponse\"\x0e\n" +
	"\fStatsRequest\"9\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xdd\x04\n" +
	"\tShortener\x12I\n" +
	"\n" +
	"ShortenURL\x12\x1c.shortener.ShortenURLRequest\x1a\x1d.shortener.ShortenURLResponse\x12U\n" +
	"\x0eShortenURLJSON\x12 .shortener.ShortenURLJSONRequest\x1a!.shortener.ShortenURLJSONResponse\x12U\n" +
	"\x0eGetOriginalURL\x12 .shortener.GetOriginalURLRequest\x1a!.shortener.GetOriginalURLResponse\x12C\n" +
	"\bBatchURL\x12\x1a.shortener.BatchURLRequest\x1a\x1b.shortener.BatchURLResponse\x12I\n" +
	"\n" +
	"GetUserURL\x12\x1c.shortener.GetUserURLRequest\x1a\x1d.shortener.GetUserURLResponse\x12R\n" +
	"\rDeleteUserURL\x12\x1f.shortener.DeleteUserURLRequest\x1a .shortener.DeleteUserURLResponse\x12:\n" +
	"\x05Stats\x12\x17.shortener.StatsRequest\x1a\x18.shortener.StatsResponse\x127\n" +
	"\x04Ping\x12\x16.shortener.PingRequest\x1a\x17.shortener.PingResponseB9Z7github.com/rookgm/shortener/tree/main/internal/grpc/pb/b\x06proto3"

var (
	file_pb_shortener_proto_rawDescOnce sync.Once
	file_pb_shortener_proto_rawDescData []byte
)

func file_pb_shortener_proto_rawDescGZIP() []byte {
	file_pb_shortener_proto_rawDescOnce.Do(func() {
		file_pb_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_shortener_proto_rawDesc), len(file_pb_shortener_proto_rawDesc)))
	})
	return file_pb_shortener_proto_rawDescData
}

var file_pb_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pb_shortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),      // 0: shortener.ShortenURLRequest
	(*ShortenURLResponse)(nil),     // 1: shortener.ShortenURLResponse
	(*ShortenURLJSONRequest)(nil),  // 2: shortener.ShortenURLJSONRequest
	(*ShortenURLJSONResponse)(nil), // 3: shortener.ShortenURLJSONResponse
	(*GetOriginalURLRequest)(nil),  // 4: shortener.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil), // 5: shortener.GetOriginalURLResponse
	(*BatchURLItem)(nil),           // 6: shortener.BatchURLItem
	(*BatchURLRequest)(nil),        // 7: shortener.BatchURLRequest
	(*BatchURLResponse)(nil),       // 8: shortener.BatchURLResponse
	(*UserURLItem)(nil),            // 9: shortener.UserURLItem
	(*GetUserURLRequest)(nil),      // 10: shortener.GetUserURLRequest
	(*GetUserURLResponse)(nil),     // 11: shortener.GetUserURLResponse
	(*DeleteUserURLRequest)(nil),   // 12: shortener.DeleteUserURLRequest
	(*DeleteUserURLResponse)(nil),  // 13: shortener.DeleteUserURLResponse
	(*StatsRequest)(nil),           // 14: shortener.StatsRequest
	(*StatsResponse)(nil),          // 15: shortener.StatsResponse
	(*PingRequest)(nil),            // 16: shortener.PingRequest
	(*PingResponse)(nil),           // 17: shortener.PingResponse
}
var file_pb_shortener_proto_depIdxs = []int32{
	6,  // 0: shortener.BatchURLRequest.orig_urls:type_name -> shortener.BatchURLItem
	6,  // 1: shortener.BatchURLResponse.short_urls:type_name -> shortener.BatchURLItem
	9,  // 2: shortener.GetUserURLResponse.urls:type_name -> shortener.UserURLItem
	0,  // 3: shortener.Shortener.ShortenURL:input_type -> shortener.ShortenURLRequest
	2,  // 4: shortener.Shortener.ShortenURLJSON:input_type -> shortener.ShortenURLJSONRequest
	4,  // 5: shortener.Shortener.GetOriginalURL:input_type -> shortener.GetOriginalURLRequest
	7,  // 6: shortener.Shortener.BatchURL:input_type -> shortener.BatchURLRequest
	10, // 7: shortener.Shortener.GetUserURL:input_type -> shortener.GetUserURLRequest
	12, // 8: shortener.Shortener.DeleteUserURL:input_type -> shortener.DeleteUserURLRequest
	14, // 9: shortener.Shortener.Stats:input_type -> shortener.StatsRequest
	16, // 10: shortener.Shortener.Ping:input_type -> shortener.PingRequest
	1,  // 11: shortener.Shortener.ShortenURL:output_type -> shortener.ShortenURLResponse
	3,  // 12: shortener.Shortener.ShortenURLJSON:output_type -> shortener.ShortenURLJSONResponse
	5,  // 13: shortener.Shortener.GetOriginalURL:output_type -> shortener.GetOriginalURLResponse
	8,  // 14: shortener.Shortener.BatchURL:output_type -> shortener.BatchURLResponse
	11, // 15: shortener.Shortener.GetUserURL:output_type -> shortener.GetUserURLResponse
	13, // 16: shortener.Shortener.DeleteUserURL:output_type -> shortener.DeleteUserURLResponse
	15, // 17: shortener.Shortener.Stats:output_type -> shortener.StatsResponse
	17, // 18: shortener.Shortener.Ping:output_type -> shortener.PingResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_shortener_proto_init() }
func file_pb_shortener_proto_init() {
	if File_pb_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_shortener_proto_rawDesc), len(file_pb_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_shortener_proto_goTypes,
		DependencyIndexes: file_pb_shortener_proto_depIdxs,
		MessageInfos:      file_pb_shortener_proto_msgTypes,
	}.Build()
	File_pb_shortener_proto = out.File
	file_pb_shortener_proto_goTypes = nil
	file_pb_shortener_proto_depIdxs = nil
}
